### ISSUE TITLE
FCMDevice table

### ISSUE THREAD

**Issue by Fado35** [xtrinch/fcm-django#146]
Hello,

I did all setup things on my project. I want to send notifications to devices but my FCMDevice table is empty. How can i make the users register here automatically. And how can i get their registration_id? Im sharing my codes here. Thank you.

Settings.py

INSTALLED_APPS = [
   
    'fcm_django',
]

FCM_DJANGO_SETTINGS = {
         # default: _('FCM Django')
        "APP_VERBOSE_NAME": "app",
         # Your firebase API KEY
        "FCM_SERVER_KEY": "[key from firebase]",
         # true if you want to have only one active device per registered user at a time
         # default: False
        "ONE_DEVICE_PER_USER": False,
         # devices to which notifications cannot be sent,
         # are deleted upon receiving error response from FCM
         # default: False
        "DELETE_INACTIVE_DEVICES": False,
}

Views.py

`from fcm_django.models import FCMDevice
devices = FCMDevice.objects.all()
    devices.send_message(title="Title", body="Message", data={"test": "test"})`

**Comment by Sermodi** [comment]
Did you solve it?

**Comment by Fado35** [comment]
Hello, no im still waiting for the answer. Can you help me about it?

**Comment by SilverStrings024** [comment]
I have no idea because I just started looking into this package not even an hour ago but I would guess that you can either over ride the save method in your model and call `FCMDevice.objects.create(your=info, goes=here)` or you can set up a pre_save or post_save signal to create the object. Personally I would opt to use an asynchronous task to create and link the objects while the user is redirected to an input screen for the OTP. When they get the code, they will enter it.

**Comment by xtrinch** [comment]
You are responsible for creating the FCM Device objects, they are not created automatically. As @SilverStrings024 said, you will need to call `FCMDevice.objects.create(your=info, goes=here)` somewhere in your app.
