### ISSUE TITLE
Migration issue with DEFAULT_AUTO_FIELD

### ISSUE THREAD

**Issue by bandirom** [xtrinch/fcm-django#193]
Hi!
There is an issue with ID field

Django 3.2.11
Python 3.10.1
fcm_django 1.0.7

![Screenshot_14](https://user-images.githubusercontent.com/46032838/148526054-4ae62534-e9be-4194-8fd2-46b6813d63c5.png)

By default I have in my project
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

But if we check created migration:

![image](https://user-images.githubusercontent.com/46032838/148527240-ce6facbc-df01-42f3-8dbe-771ad2829061.png)

**Comment by xtrinch** [comment]
It's generating the exact same migration as the 0008?

**Comment by bandirom** [comment]
In the 0008 we have AutoField

![image](https://user-images.githubusercontent.com/46032838/148531690-02222d07-f92e-4fff-ba9e-4b77beef3a38.png)

**Comment by xtrinch** [comment]
Uff yeah it's a tricky one because this package overrides the default auto field.. I think it should perhaps do it on a model basis not project-wide, because it's presumptuous..

![image](https://user-images.githubusercontent.com/7256491/148532790-92d4f44c-dad7-4775-9b4f-bce39301b674.png)

I'll glady accept a PR on the matter

**Comment by bandirom** [comment]
Create PR :)
https://github.com/xtrinch/fcm-django/pull/194
Thank you!

**Comment by xtrinch** [comment]
Fixed in 1.0.8
