### ISSUE TITLE
USER_MODEL configuration in FCM_DJANGO_SETTINGS not working

### ISSUE THREAD

**Issue by phongng-it** [xtrinch/fcm-django#250]
I don't understand why you edit the user field like this:
![image](https://github.com/xtrinch/fcm-django/assets/34709818/dc59bbf6-97d1-4758-8339-ae8c61a551a9)

**Comment by merwok** [comment]
what do you mean? this looks like the normal way to configure a foreign key to the user model.

**Comment by xtrinch** [comment]
Could you define "not working"? You're not supposed to configure the user model for fcm django in the fcm django settings as the library user, you're supposed to use django settings to configure your default user model, which will in turn be picked up by fcm-django.

**Comment by xtrinch** [comment]
The user model setting is a global django setting, there is no user model setting of fcm-django, as mentioned above in my previous comment.

I suggest you read https://docs.djangoproject.com/en/4.2/topics/auth/customizing/ thorougly. The setting is called AUTH_USER_MODEL

**Comment by joeyorlando** [comment]
I ended up having to create my own fork of this repo because of this. [This](https://github.com/grafana/fcm-django/commit/9653bd7dee9483db8ec1dadf853c00660ba50440) was the commit exactly related to this.

**Comment by xtrinch** [comment]
@phongng-it I agree, the code should be structured in a way that it is always taken from AUTH_USER_MODEL rather than defaulted to AUTH_USER_MODEL in the settings. But if users don't go around configuring USER_MODEL in fcm_django settings (which I'm not sure why they are since it's not mentioned in the docs) it's fine. Something to be worked on.

@joeyorlando I suspect your use case is different than what this library intended. Your django AUTH_USER_MODEL is not the same as the user you'd like to use for fcm-django? Or why are you overriding fcm django's USER_MODEL?
