### ISSUE TITLE
Question: Need help in understanding

### ISSUE THREAD

**Issue by just10minutes** [xtrinch/fcm-django#8]
Hi,

I would like to know whether my approach is correct in order to  use this wonderful package.

1. Create an mobile app and ask users to install the app. During the installation the app should communicate to my Django app and update FCM devices model/table with their device id's

2. Once users register then using the send message option i can send message to their device.

3. On Firebase I should add my newly built android app details as well so it can communicate to firebase App server.

Is my understanding correct?

Thanks,
Raj

**Comment by xtrinch** [comment]
Depends - if you want to send messages to an installation of an app, you will not connect your FCM django model with a user, otherwise you will.

My suggestion (which is also the easiest way of implementing this) is using the DRF viewsets provided in this package by including them in your urls.py. Via these URL's, users can register their devices.

If you go the unathenticated route, you will register a device upon installation and refresh token when needed. If you connect your FCM django models with users, you will register devices upon logging in and remove tokens upon logging out.

And yes, all the details that firebase needs for its operation should be entered in the firebase console.

**Comment by just10minutes** [comment]
@xtrinch Thanks a lot for coming back to me on this.

Please do not mind my questions, i am still keeping my baby steps in this process.

> My suggestion (which is also the easiest way of implementing this) is using the DRF viewsets provided in this package by including them in your urls.py. Via these URL's, you should register devices in the background processes of your app.

Lets assume i go with DRF. 
1. so my mobile app should call the below url somehow at the background during the installation process? 
mysite.com/devices   
or /also
2. Person visiting the url (mysite.com/devices) through chrome browser will be able to register and be able receive notifications through the firebase notification for web method?

> If you go the unathenticated route, you will register a device upon installation and refresh token when needed. If you connect your FCM django models with users, you will register devices upon logging in and remove tokens upon logging out.

My idea was to anyway register the user only once during the first installation only, not every time the user opens the app, so your first statement is what is applicable for me.


Thanks a lot for your time and support

**Comment by xtrinch** [comment]
@just10minutes 

Yes, at some point your mobile app should register your device. I would say after the installation is finished, and then ofcourse refresh the token when it expires.

For web notifications you should register your web clients the same way you register your mobile devices. As this is fairly new, I'll be adding 'web' type to FCMDevice token. I'm also preparing an example app how to use it with service workers. You will also be needing HTTPS for that, since service workers do not work on HTTP. There are many tutorials on web, but I'll post a link to my example project when I'm finished, that should be sometime this week.

**Comment by just10minutes** [comment]
Thank you @xtrinch , i will try my luck with this.

I am planning to build a normal NativeScript mobile app just to check whether i will be able to send the message or not to my mobile.

Thanks for all your support.

**Comment by xtrinch** [comment]
@just10minutes I'm being very late, but here's the example project I was talking about:

https://github.com/xtrinch/fcm-django-web-demo

**Comment by just10minutes** [comment]
@xtrinch  thank you very much. I will have a look at this.
